id: I5BBDE46A
legacy_id: P006829
ocr_import_info:
  bdrc_scan_id: W1GS49554
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T12:22:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T04:22:41.802716+00:00'
last_modified: 2022-08-27 12:23:07.451443
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1GS49554
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1GS49554
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མགོ་ལོག་རིག་གནས་ལོ་རྒྱུས། （༢）
statistics:
  ocr_word_mean_confidence_index: 0.8572096393491666
  ocr_word_median_confidence_index: 0.9200000166893005
quality: null
bases:
  I1GS49572:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS49572
      total_pages: 148
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS49572.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8572096393491666
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
