id: P006829
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:25:20.968917
source_metadata:
  id: bdr:W1GS49554
  title: མགོ་ལོག་རིག་གནས་ལོ་རྒྱུས། （༢）
  author: ''
  volumes:
    d5970b20f9be426caadaef01fc48727e:
      image_group_id: I1GS49572
      title: ''
      volume_number: 1
      total_pages: 148
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
