id: P006829
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS49554
  title: མགོ་ལོག་རིག་གནས་ལོ་རྒྱུས། （༢）
  author: ''
  volumes:
    d5970b20f9be426caadaef01fc48727e:
      image_group_id: I1GS49572
      title: ''
      volume_number: 1
      total_pages: 148
